### ISSUE TITLE
Regular Bundle (and Regular Large Bundle) Sizes not modifiable using the config.

### ISSUE THREAD

**Issue by Mnky313** [BelgianSalamander/MoreBundles#1]
The values for the size of the Regular and Regular Large Bundle don't update when changing them in the config.

I believe it's because they are hardcoded in the Items.java file.

to reproduce just change the size of either of them in the config file and restart the game, the value is changed in the config but does not change the size in game.

(Also the mod is named 'Example Mod' in MultiMC (you need to change the name, description, and authors section in fabric.mod.json))

**Comment by BelgianSalamander** [comment]
Should be fixed in [new version](https://www.curseforge.com/minecraft/mc-mods/more-bundles/files/3558993)
