### ISSUE TITLE
Dupe Glitch 1.18.2

### ISSUE THREAD

**Issue by JuceInUse** [BelgianSalamander/MoreBundles#13]
So I was recently playing around with this lovely mod and noticed that when you right click an item into a bundle from the crafting output, it puts the item into the bundle but the items from the crafting grid stay in it. This means that you can dupe... any recipe. [Here's an example](https://cdn.discordapp.com/attachments/854349856650428416/977922443782008892/Infinite_Power.mp4)

**Comment by BelgianSalamander** [comment]
Thanks for bringing this up! This should be fixed in the latest version :)
