### ISSUE TITLE
Display conflict issue with the [New in Town] datapack?

### ISSUE THREAD

**Issue by cactusdoodad** [BelgianSalamander/MoreBundles#4]
A curious display conflict(?) with the datapack New in Town.
Conflict is between the way the bundles show the items inside and how that datapack shows it's recipes.
Not very critical as they are both still playable together but just found an interesting issue, that's all.

**Comment by BelgianSalamander** [comment]
Can you elaborate on what happens, I'm not sure I completely understand.

Thanks
