### ISSUE TITLE
[1.18.1] Conflict between Farmer's Delight and More Bundles

### ISSUE THREAD

**Issue by Quizer9O8** [BelgianSalamander/MoreBundles#9]
When starting the game Minecraft crashes right after due to a bad interaction with Farmer's Delight.

The author stated what's causing it right here:
https://bitbucket.org/n-horyzon/farmers-delight-fabric/issues/51/farmers-delight-crashes-minecraft-during

See crash log:
https://crashy.net/rnyo5VyBqz2xaTPJoNTr

**Comment by BelgianSalamander** [comment]
The morebundles version that appears in this crash (0.2.0) is outdated. A similar issue was reported here (https://github.com/BelgianSalamander/MoreBundles/issues/6) and is fixed. Could you please try with this file (https://www.curseforge.com/minecraft/mc-mods/more-bundles/files/3573607). Thanks for the help
